name: API Build and Test

on:
  push:
    branches:
      - feature/**
    paths:
      - 'api/**'
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'

jobs:
  build-api:
    name: Build API application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: install API dependencies
        run: pip install -r api/api-requirements.txt

      #- name: Run API unit test
       #run: pytest tests/test_book_api_unittest.py

      - name: build API Docker image
        run: docker build -t book_api -f Dockerfile .

