name: API and Client Build and Test

on:
  push:
    branches:
      - feature/**
    paths:
      - 'api/**'
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
      - 'client/**'

jobs:
  build-and-test:
    name: Build and Test API & Client Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install API dependencies
        run: pip install -r api/api-requirements.txt

      - name: Install Client dependencies
        run: pip install -r client/requirements.txt

      - name: Build API Docker image
        run: docker build -t book_api -f Dockerfile .

      - name: Run API Docker container
        run: |
          docker run -d -p 5000:5000 --name api-container book_api
          sleep 10  # Wait for the API to be ready

      - name: Run integration test for Client
        run: python tests/test_book_api_integration.py

      - name: Stop and remove the API container
        run: docker stop api-container && docker rm api-container
