
name: API and Client Build and Test
on:
  push:
    branches:
      - feature/**
    paths:
      - 'api/**'
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
      - 'client/**'
jobs:
  build-api:
    name: Build API/CLIENT 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install API dependencies
        run: pip install -r api/api-requirements.txt

      - name: Install Client dependencies
        run: pip install -r client/requirements.txt

      - name: Build API Docker image
        run: docker build -t book_api -f Dockerfile .

      - name: Install Trivy
        run: | 
          curl -sfL https://github.com/aquasecurity/trivy/releases/download/v0.22.0/trivy_0.22.0_Linux-64bit.tar.gz | tar xz -C /usr/local/bin

      - name: Run Trivy Scan on Docker Image
        run: trivy image book_api

      - name: Run API Docker container
        run: |
          docker run -d -p 5000:5000 --name api-container book_api
          sleep 10  # Wait for the API to be ready

      - name: Run integration test for Client
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/api
          python tests/test_book_api_integration.py

      - name: run client
        run: python client/Client.py

      - name: Stop and remove the API container
        run: docker stop api-container && docker rm api-container

  security:
    name: Security
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # <-- This is important!
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Init CodeQl
        uses: github/codeql-action/init@v2

      - name: Perform CodeQl Analysis
        uses: github/codeql-action/analyze@v2

  deploy-to-staging:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    needs: [build-api , security]  # Ensure this runs after build and security jobs are successful
    environment: staging  # Define the environment (could be 'production' or any custom name)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies for deployment
        run: |
          pip install -r api/api-requirements.txt
          pip install -r client/requirements.txt

      - name: Build API Docker image for Staging
        run: |
          docker build -t book_api_staging -f Dockerfile .

      - name: Run API Docker container for Staging
        run: |
          docker run -d -p 5000:5000 --name api-container-staging book_api_staging
          sleep 10  # Allow API to start

      - name: Deploy Client Application (e.g., Copy Files, Update, etc.)
        run: |
          python client/Client.py  # Assuming you need to run your client app

      - name: Notify Deployment Success
        run: echo "Deployment to Staging successful!"